quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://192.168.1.103:5432/postgres
quarkus.datasource.jdbc.max-size=16
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.log.handler.console.con.enable=true
quarkus.log.level=DEBUG
quarkus.log.category."org.hibernate".level=DEBUG
quarkus.log.category."org.hibernate".min-level=TRACE
quarkus.http.host=0.0.0.0
quarkus.http.port=8080
quarkus.http.auth.proactive=false

quarkus.container-image.build=false
quarkus.container-image.push=false

quarkus.banner.enabled=true